/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/89IuzpNd0R9
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Card() {
  return (
    <Card className="w-[350px]">
      <CardHeader>
        <div className="flex items-center">
          <div className="flex items-center space-x-2">
            <FlagIcon className="h-6 w-6 text-[#bd1e59]" />
            <div>
              <CardTitle>FixDex</CardTitle>
              <p className="text-sm text-gray-500">248 followers</p>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <img
          alt="Content preview"
          className="w-full"
          height="192"
          src="/placeholder.svg"
          style={{
            aspectRatio: "320/192",
            objectFit: "cover",
          }}
          width="320"
        />
        <h3 className="mt-4 text-lg font-semibold leading-tight">Ten ways to improve customer productivity</h3>
        <p className="text-sm text-blue-600">fixdex.com</p>
        <div className="flex justify-between items-center mt-4">
          <p className="text-sm text-gray-500">248 followers</p>
          <Button>Learn more</Button>
        </div>
      </CardContent>
    </Card>
  )
}


function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 4-1V3s-1 1-4 1-5-2-8-2-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
